name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Atualiza todo dia à meia-noite

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Gerar animação da cobra
        uses: Platane/snk@v2
        with:
          github_user_name: GiovanniDSouza
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit e push
        uses: EndBug/add-and-commit@v7
        with:
          branch: output
          message: "Atualizando a animação da cobra"
